# tmux attach to connect or create session
new-session -n $HOST

# settings
set -g mouse on
set -g default-terminal 'tmux-256color'
# note that single vs double quote seems to matter
set-option -ga terminal-overrides ',xterm*:RGB:sitm=\E[3m'
set-option -sg escape-time 10

# open new pane in same path by default
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'arcticicestudio/nord-tmux'

# init tpm
# prefix + I to run install
run -b '~/.tmux/plugins/tpm/tpm'
