wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [36, 60, 120]
    rows: [8, 8, 8, 8, 60]
  refreshInterval: 1
  mods:
    clocks_a:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        New York: "America/New_York"
        California: "America/Los_Angeles"
        Beijing: "Asia/Shanghai"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
      title: "Clocks"
      type: "clocks"
      focusable: true
    feedreader:
      enabled: true
      feeds:
      - https://feeds.bbci.co.uk/news/rss.xml
      feedLimit: 10
      position:
        top: 4
        left: 0
        width: 2
        height: 1
      refreshInterval: 14400
      focusable: true
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 150
      title: "IP Info"
      focusable: true
    prettyweather:
      enabled: true
      city: "New York"
      position:
          top: 2
          left: 0
          height: 1
          width: 1
      refreshInterval: 5m
      unit: "m"
      view: 0
      language: "en"
      title: "Weather"
      focusable: true
    power:
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      title: "Power"
      focusable: true
    tasks:
      args: []
      cmd: "task"
      enabled: true
      position:
        top: 0
        left: 1
        height: 4
        width: 1
      pty: true
      refreshInterval: "10m"
      type: cmdrunner
      title: "Tasks"
      focusable: true
