# tmux attach to connect or create session
new-session -n $HOST

# settings
set -g mouse on
set -g default-terminal 'tmux-256color'
# note that single vs double quote seems to matter
set-option -ga terminal-overrides ',xterm*:Tc:sitm=\E[3m'
set-option -sg escape-time 10

# open new pane in same path by default
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# init tpm
# prefix + I to run install
run -b '~/.tmux/plugins/tpm/tpm'

# ==== styling ====
set -g status-bg black
set -g status-fg white

set -g status-justify left
set -g status-right-length 60
set -g status-left "#[fg=black,bg=blue,bold] #S #[fg=blue,bg=black,nobold,noitalics,nounderscore]"
set -g status-right "#{prefix_highlight}#[fg=brightblack,bg=black,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] %Y-%m-%d #[fg=white,bg=brightblack,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] %H:%M #[fg=cyan,bg=brightblack,nobold,noitalics,nounderscore]#[fg=black,bg=cyan] #(os_logo) #[fg=black,bg=cyan,bold] #H "

set -g window-status-format "#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I #[fg=white,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#W #F #[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W #F #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-separator ""

set -g status-interval 15

set -g pane-border-style fg=brightblack
set -g pane-active-border-style fg=cyan
set -g display-panes-colour black
set -g display-panes-active-colour brightblack

setw -g clock-mode-colour cyan

set -g message-style fg=cyan,bg=brightblack
set -g message-command-style fg=cyan,bg=brightblack
