# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$sudo$directory$character"""
right_format = ""

# Inserts a blank line between shell prompts
add_newline = false

[hostname]
ssh_symbol = '@'

[directory]
read_only = ''
home_symbol = '~'
truncation_symbol = '…/'
style = 'bold blue'

[line_break]
disabled = true

[aws]
disabled = true

[time]
disabled = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[\$](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol   = '[\$](bold red)'

[sudo]
symbol = '# '

[git_branch]
symbol = ''

[git_status]
ahead = '↑'
behind = '↓'
diverged = '↕'
renamed = '⇾'
deleted = 'x'

