# Create dvi file
make-dvi:
  latex *.tex

# Create pdf file
make-pdf: make-dvi
  dvipdfm *.dvi

clean:
  rm *.aux *.log *.dvi

iterate:
  ls *.tex | entr -s 'killall Preview; just make-pdf; open *.pdf'
