#!/usr/bin/env python3
import os
import openai
import sys

MODEL = 'gpt-3.5-turbo'


def main() -> None:
    with open(f"{os.getenv('HOME')}/.config/openai.key", 'r') as keyfile:
        openai.api_key = keyfile.read().strip()
    input = ' '.join(sys.argv[1:]).strip()

    if not input:
        return
    response = openai.ChatCompletion.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": input},
        ]
    )
    print(response['choices'][0]['message']['content'])


if __name__ == "__main__":
    main()
