#!/usr/bin/env bash

set -e

name="${1%.*}"

rate=24
if [[ -n "${2}" ]]; then
  rate="${2}"
fi

tmp_input="tmp_input"
tmp_output="tmp_output"

if ! [[ -d "${tmp_input}" ]]; then
  mkdir "$tmp_input"
  ffmpeg -i "${1}" -qscale:v 1 -qmin 1 -qmax 1 -vsync 0 "${tmp_input}/frames%08d.jpg"
fi

if ! [[ -d "${tmp_output}" ]]; then
  mkdir "$tmp_output"
  realesrgan-ncnn-vulkan -m "$HOME/.local/bin/models" -i "${tmp_input}" \
    -o "${tmp_output}" -n realesr-animevideov3 -s 4 -f jpg
fi

ffmpeg -i "${tmp_output}/frames%08d.jpg" -i "${1}" -map "0:v:0" -map "1:a:0?" -c:a copy \
  -c:v libx264 -r "${rate}" -pix_fmt yuv420p "${name}_2x.mp4"

rm -rf "${tmp_input}"
rm -rf "${tmp_output}"

echo "Successfully upscaled ${1} to ${name}_2x.mp4."
