#!/usr/bin/env bash

# 1. get a list of all currently running zellij tabs by calling `zellij action
#    query-tab-names`; record the list.
# 2. change current tab name by calling `zellij action rename-tab TEMP`;
# 3. get a list of all currently running zellij tabs by calling `zellij action
#    query-tab-names` again; record the list, which should now have one
#    different row from the original list, which is now `TEMP`.
# 4. Using the *changed* row to identify the *original* tab name and record it.
#    The index of the changed row should be the same, so we can first find the
#    index of the row named "TEMP", then use the corresponding row from original.
# 5. use `zellij action rename-tab ...` to restore the original name.

# Example code to achieve the above steps:

set -e

original_tabs=$(zellij action query-tab-names)
zellij action rename-tab TEMP

new_tabs=$(zellij action query-tab-names)
readarray -t original_array <<< "$original_tabs"
readarray -t new_array <<< "$new_tabs"

temp_index=-1
for i in "${!new_array[@]}"; do
    if [[ "${new_array[i]}" == "TEMP" ]]; then
        temp_index=$i
        break
    fi
done
if [[ $temp_index -eq -1 ]]; then
    exit 1
fi

original_name="${original_array[temp_index]}"
zellij action rename-tab "$original_name"

echo $original_name

